#############################
## GitHub Actions CI Tests ##
#############################
#
# This can be kicked off manually in the Actions tab of GitHub
# It will also run nightly at 2pm
# It will run on any pull request, except non-code changes
# (images, markdown files, )
#
name: CI Linting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - features-linting
  push:
    branches:
      - features-linting

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          [
            "linting",
            "doclinting",
            "yamllint",
            "doctests",
          ]
    name: ${{ matrix.job }} tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            setup.cfg
            requirements_dev.txt
      - name: Install dependencies
        run: pip install tox
      - name: Run the tests
        run: tox -e ${{ matrix.job }}
