#############################
## GitHub Actions CI Tests ##
#############################
#
# This can be kicked off manually in the Actions tab of GitHub
# It will also run nightly at 2pm
# It will run on any pull request, except non-code changes
# (images, markdown files, )
#
name: CI Unit Tests With Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - ci-unit-tests-coverage
  push:
    branches:
      - ci-unit-tests-coverage

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .
          pip install tox
          pip install tqdm
      - name: Run the python tests (with coverage)
        id: pythontests
        run: tox -e py310 -- --cov=sqlfluff -n 2 test -m "not integration" --durations=16 --verbosity=0
      - name: Test the example files tests
        id: exampletests
        run: |
          for file in examples/*
          do
            echo "Running $file"
            python "$file"
          done
      # Add a step to explicitly check coverage
      - name: Check coverage
        run: |
          pip install coverage
          coverage combine
          coverage report --fail-under=95 --show-missing --omit "*templaters/dbt.py,*/dbt_templater/*"
          # TODO: Current coverage is around 94%. We're setting threshold to 95% to 
          # provide a realistic target while encouraging continuous improvement.
