#############################
## GitHub Actions CI Tests ##
#############################
#
# This can be kicked off manually in the Actions tab of GitHub
# It will also run nightly at 2pm
# It will run on any pull request, except non-code changes
# (images, markdown files, )
#
name: CI Build and Compilation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - features-build-compilation
  push:
    branches:
      - features-build-compilation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install tox
      - name: Run mypy
        id: mypy
        continue-on-error: true
        run: tox -e "mypy"
      - name: Run mypyc
        id: mypyc
        continue-on-error: true
        run: tox -e "mypyc"
      - name: Check if any step failed
        if: ${{ steps.mypy.outcome == 'failure' || steps.mypyc.outcome == 'failure' }}
        run: exit 1
