name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      RAW_LOG: pre-commit.log
      CS_XML: pre-commit.xml
      SKIP: no-commit-to-branch
      PRE_COMMIT_NO_WRITE: 1
    steps:
      - run: sudo apt-get update && sudo apt-get install cppcheck
        if: false
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        if: false
        with:
          cache: pip
          python-version: 3.12.1
      - run: python -m pip install pre-commit
      # Cache pre-commit for speed
      # Note: PRE_COMMIT_NO_WRITE=1 prevents hooks from writing changes to disk,
      # but pre-commit still reports "files were modified" when hooks would make changes.
      # The Run pre-commit hooks step handles this by checking for actual errors vs. just "files were modified" messages.
      - uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml', '.pre-commit-config-ci.yaml') }}
      - name: Run pre-commit hooks
        # Note: We use 'set +e' to prevent the script from exiting immediately when
        # pre-commit fails, allowing us to properly handle fix-* branches that are
        # expected to have pre-commit failures. We capture the exit code using PIPESTATUS
        # to still be able to check if pre-commit failed.
        run: |
          # Disable exit on error to prevent early termination
          set +e
          set -o pipefail
          # Initialize a flag to track whether we should skip failure checks
          SKIP_FAILURE_CHECKS=false

          # Clean pre-commit cache to remove phantom files
          pre-commit clean
          pre-commit gc
          # Remove any existing log file and create a new empty one
          rm -f ${RAW_LOG}
          touch ${RAW_LOG}
          # Run pre-commit on all files in check-only mode and ensure output is captured
          pre-commit run --show-diff-on-failure --color=always --all-files -c .pre-commit-config-ci.yaml | tee ${RAW_LOG}
          # Capture the exit code
          PRE_COMMIT_EXIT_CODE=${PIPESTATUS[0]}

          # Count the number of failures and "files were modified" messages
          FAILED_COUNT=$(grep -c "Failed" ${RAW_LOG} || echo 0)
          MODIFIED_COUNT=$(grep -c "files were modified by this hook" ${RAW_LOG} || echo 0)
          ERROR_COUNT=$(grep -c "^[^-].*error:" ${RAW_LOG} || echo 0)

          echo "Found ${FAILED_COUNT} failures, ${MODIFIED_COUNT} 'files were modified' messages, and ${ERROR_COUNT} errors"

          # Debug log file content
          echo "Log file size: $(wc -l < ${RAW_LOG}) lines"
          echo "First few lines of log file:"
          head -n 5 ${RAW_LOG}

          # Get the branch name from GitHub environment variables
          # For pull requests, GITHUB_HEAD_REF contains the source branch name
          # For direct pushes, we extract it from GITHUB_REF
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Current branch name: ${BRANCH_NAME}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"

          # Debug branch name character by character to detect any invisible characters
          echo "Branch name character by character:"
          for (( i=0; i<${#BRANCH_NAME}; i++ )); do
            char="${BRANCH_NAME:$i:1}"
            printf "Position %d: %s (ASCII: %d)\n" "$i" "$char" "'$char"
          done

          # Check if we're on a branch specifically fixing formatting issues
          # Using string contains operator for substring matching anywhere in the branch name
          # Note: When using =~ operator in bash, the regex pattern should not be quoted
          echo "Checking if branch name matches formatting fix pattern..."
          # Use string prefix matching instead of regex for more reliable behavior
          if [[ "${BRANCH_NAME}" == fix-* ]]; then
            echo "Branch starts with 'fix-': YES"
            # Any branch that starts with 'fix-' is considered a formatting fix branch
            echo "::warning::On branch ${BRANCH_NAME} which starts with 'fix-' - allowing pre-commit failures"
            # Set flag to skip failure checks
            SKIP_FAILURE_CHECKS=true
          else
            echo "Branch starts with 'fix-': NO"
          fi

          # First check if we should skip failure checks (for fix-* branches)
          if [ "$SKIP_FAILURE_CHECKS" = true ]; then
            echo "::notice::Skipping failure checks because this is a formatting fix branch"
            # Reset exit code to 0 to prevent workflow failure when we're on a formatting fix branch
            exit 0
          # Only then check for failures if we're not skipping checks
          elif [ "${PRE_COMMIT_EXIT_CODE}" -ne 0 ] || [ "${FAILED_COUNT}" -gt 0 ]; then
            echo "Pre-commit exit code: ${PRE_COMMIT_EXIT_CODE}"
            # If all failures are just "files were modified" messages, consider it a success
            if [ "${FAILED_COUNT}" -eq "${MODIFIED_COUNT}" ]; then
              echo "::warning::Pre-commit reported 'Failed' but these were just 'files were modified' messages"
              # Success - no need to exit
            # If we have actual errors (failures without "files were modified"), exit with error
            elif [ "${MODIFIED_COUNT}" -eq 0 ]; then
              echo "::error::Pre-commit found actual issues that need to be fixed"
              exit 1
            # If we have a mix of "files were modified" and other failures, check for actual errors
            elif [ "${ERROR_COUNT}" -gt 0 ]; then
              echo "::error::Pre-commit found actual errors that need to be fixed"
              exit 1
            else
              echo "::warning::Pre-commit reported 'files were modified' but no actual errors were found"
              # Success - no need to exit
            fi
          fi
      - name: Convert Raw Log to Checkstyle format (launch action)
        uses: mdeweerd/logToCheckStyle@v2024.3.5
        with:
          in: ${{ env.RAW_LOG }}
          out: ${{ env.CS_XML }}
      - uses: actions/cache/save@v4
        if: ${{ ! cancelled() }}
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml', '.pre-commit-config-ci.yaml') }}
      - name: Provide log as artifact
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: precommit-logs
          path: |
            ${{ env.RAW_LOG }}
            ${{ env.CS_XML }}
          retention-days: 2
